# Generated by Django 4.0.1 on 2022-02-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=25)),
                ('product_category', models.CharField(max_length=25)),
                ('product_price', models.CharField(max_length=10)),
                ('product_picture', models.FileField(default='product.jpg', upload_to='product')),
            ],
            options={
                'db_table': 'product_tbl',
            },
        ),
    ]
