# Generated by Django 4.0.1 on 2022-02-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_remove_order_payment_state_order_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
    ]
