# Generated by Django 4.0.1 on 2022-02-20 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_remove_order_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
    ]
